function AllCollectionsList() {
  return [
    {
      name: "Real",
      title: "Натуральный линолеум</br>Marmoleum Real",
      property: "дизайна под мрамор",
      count: 33,
      img: "./assets/images/collections/recomended_collections/real.png",
      katalog_img: './assets/images/katalog/real.png',
      link: "marmoleum-real.htm",
    },
    // {
    //   name: "Striato textura",
    //   property: "",
    //   img:
    //     "./assets/images/collections/recomended_collections/striato_textura.png",
    //   link: "marmoleum-striato-textura.htm",
    // },
    {
      name: "Walton cirrus",
      title: "Натуральный линолеум</br>Marmoleum Cirrus",
      property: "однотонных дизайнов",
      count: 11,
      img:
        "./assets/images/collections/recomended_collections/walton_cirrus.png",
        katalog_img: './assets/images/katalog/walton-cirrus.png',
      link: "marmoleum-walton-cirrus.htm",
    },
    {
      name: "Cocoa",
      title: "Натуральный линолеум</br>Marmoleum Cocoa",
      property: "дизайнов со скорлупкой какао",
      count: 5,
      img: "./assets/images/collections/recomended_collections/cocoa.png",
      katalog_img: './assets/images/katalog/cocoa.png',
      link: "marmoleum-cocoa.htm",
    },
    {
      name: "Slate",
      title: "Натуральный линолеум</br>Marmoleum Slate",
      property: "дизайнов под камень",
      count: 5,
      img: "./assets/images/collections/recomended_collections/slate.png",
      katalog_img: './assets/images/katalog/slate.png',
      link: "marmoleum-slate.htm",
    },
    {
      name: "Vivace",
      title: "Натуральный линолеум</br>Marmoleum Vivace",
      property: "ярких дизайнов",
      count: 9,
      img: "./assets/images/collections/recomended_collections/vivace.png",
      katalog_img: './assets/images/katalog/vivace.png',
      link: "marmoleum-vivace.htm",
    },
    {
      name: "Splash",
      title: "Натуральный линолеум</br>Marmoleum Splash",
      property: "дизайнов с яркими акцентами",
      count: 6,
      img: "./assets/images/collections/recomended_collections/splash.png",
      katalog_img: './assets/images/katalog/splash.png',
      link: "marmoleum-splash.htm",
    },
    {
      name: "Fresco",
      title: "Натуральный линолеум</br>Marmoleum Fresco",
      property: "дизайнов под мрамор",
      count: 38,
      img: "./assets/images/collections/recomended_collections/fresco.png",
      katalog_img: './assets/images/katalog/fresco.png',
      link: "marmoleum-fresco.htm",
    },
    {
      name: "Terra",
      title: "Натуральный линолеум</br>Marmoleum Terra",
      property: "нейтральных дизайна",
      count: 4,
      img: "./assets/images/collections/recomended_collections/terra.png",
      katalog_img: './assets/images/katalog/terra.png',
      link: "marmoleum-terra.htm",
    },
    {
      name: "Concrete",
      title: "Натуральный линолеум</br>Marmoleum Concrete",
      property: "дизайна под бетон",
      count: 33,
      img: "./assets/images/collections/recomended_collections/concrete.png",
      katalog_img: './assets/images/katalog/concrete.png',
      link: "marmoleum-concrete.htm",
    },
    {
      name: "Ohmex",
      title: "Натуральный линолеум</br>Marmoleum Ohmex",
      property: "дизайнов токорассеивающего покрытия",
      count: 6,
      img: "./assets/images/collections/recomended_collections/ohmex.png",
      katalog_img: './assets/images/katalog/ohmex.png',
      link: "marmoleum-ohmex.htm",
    },
    {
      name: "Sport",
      title: "Натуральный линолеум</br>Marmoleum Sport",
      property: "дизайнов спортивного покрытия",
      count: 13,
      img: "./assets/images/collections/recomended_collections/sport.png",
      katalog_img: './assets/images/katalog/sport.png',
      link: "marmoleum-sport.htm",
    },
    {
      name: "Piano",
      title: "Натуральный линолеум</br>Marmoleum Piano",
      property: "насыщенных дизайнов",
      count: 19,
      img: "./assets/images/collections/recomended_collections/piano.png",
      katalog_img: './assets/images/katalog/piano.png',
      link: "marmoleum-piano.htm",
    },
    {
      name: "Striato",
      title: "Натуральный линолеум</br>Marmoleum Striato",
      property: "дизайнов в полоску",
      count: 20,
      img: "./assets/images/collections/recomended_collections/concrete.png",
      katalog_img: './assets/images/katalog/striato.png',
      link: "marmoleum-striato.htm",
    },
    {
      name: "Walton Uni",
      title: "Натуральный линолеум</br>Marmoleum Walton Uni",
      property: "однотонных дизайна",
      count: 4,
      img: "./assets/images/collections/recomended_collections/walton_uni.png",
      katalog_img: './assets/images/katalog/walton-uni.png',
      link: "marmoleum-walton-uni.htm",
    },
    {
      name: "Acoustic",
      title: "Натуральный линолеум</br>Marmoleum Acoustic",
      property: "дизайнов с акустикой до 14 дБ",
      count: 6,
      img: "./assets/images/collections/recomended_collections/acoustic.png",
      katalog_img: './assets/images/katalog/acoustic.png',
      link: "marmoleum-acoustic.htm",
    },
    {
      name: "Decibel",
      title: "Натуральный линолеум</br>Marmoleum Decibel",
      property: "дизайнов с акустикой до 18 дБ",
      count: 26,
      img: "./assets/images/collections/recomended_collections/decibel.png",
      katalog_img: './assets/images/katalog/decibel.png',
      link: "marmoleum-decibel.htm",
    },
    // {
    //   name: "Meets Harlekino",
    //   property: "",
    //   img: "./assets/images/collections/recomended_collections/harlekino.png",
    //   link: "marmoleum-harlekino.htm",
    // },
    // {
    //   name: "Meets Plato",
    //   property: "",
    //   img: "./assets/images/collections/recomended_collections/plato.png",
    //   link: "marmoleum-plato.htm",
    // },
    // {
    //   name: "Meets Proust",
    //   property: "",
    //   img: "./assets/images/collections/recomended_collections/proust.png",
    //   link: "marmoleum-proust.htm",
    // },
    {
      name: "Bulletin Board",
      title: "Покрытие для мебели и стен Bulletin Board",
      property: "дизайнов для досок объявлений",
      count: 15,
      img:
        "./assets/images/collections/recomended_collections/bulletinboard.png",
        katalog_img: './assets/images/katalog/bulletin-board.png',
      link: "marmoleum-bulletin-board.htm",
    },
    {
      name: "Furniture Linoleum",
      title: "Покрытие для мебели</br>Furniture Linoleum",
      property: "скандинавский дизайн",
      count: 21,
      img: "./assets/images/collections/recomended_collections/desktop.png",
      katalog_img: './assets/images/katalog/furniture-linoleum.png',
      link: "marmoleum-furniture-linoleum.htm",
    },
    {
      name: "Corkment",
      title: "Пробковая подложка под натуральный линолеум",
      property: null,
      count: null,
      img: "./assets/images/collections/recomended_collections/corkment.png",
      katalog_img: './assets/images/katalog/corkment.png',
      link: "marmoleum-corkment.htm",
    },
  ];
}
