function DLWCollectionsList() {
    return [
      {
        name: "DLW Marmorette",
        title: "DLW Marmorette",
        property: "",
        count: 64,
        img: "./assets/images/collections/dlw_collections/marmorette.png",
        katalog_img: './assets/images/collections/dlw_collections/marmorette.png',
        link: "dlw_marmorette.htm",
      },
      {
        name: "DLW Colorette",
        title: "DLW Colorette",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/colorette.png",
        katalog_img: './assets/images/collections/dlw_collections/colorette.png',
        link: "dlw_colorette.htm",
      },
      {
        name: "DLW Uni Walton",
        title: "Marmoleum</br>Uni Walto",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/uni_walton.png",
        katalog_img: './assets/images/collections/dlw_collections/uni_walton.png',
        link: "dlw_uni-walton.htm",
      },
      {
        name: "DLW Arabesque",
        title: "Marmoleum</br>Arabesque",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/arabesque.png",
        katalog_img: './assets/images/collections/dlw_collections/arabesque.png',
        link: "dlw_arabesque.htm",
      },
      {
        name: "DLW Lino Art",
        title: "DLW Lino Art",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/lino_art.png",
        katalog_img: './assets/images/collections/dlw_collections/lino_art.png',
        link: "dlw_lino-art.htm",
      },
      {
        name: "DLW Linodur",
        title: "DLW Linodur</br>4mm",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/linodur.png",
        katalog_img: './assets/images/collections/dlw_collections/linodur.png',
        link: "dlw_linodur.htm",
      },
      {
        name: "Acoustic Plus",
        title: "Acoustic Plus</br>19 dB",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/acoustic_plus.png",
        katalog_img: './assets/images/collections/dlw_collections/acoustic_plus.png',
        link: "dlw_acoustic-plus.htm",
      },
      {
        name: "Marmorette Acoustic",
        title: "Marmorette</br>Acoustic 15 dB",
        property: "",
        count: '',
        img: "./assets/images/collections/dlw_collections/acoustic.png",
        katalog_img: './assets/images/collections/dlw_collections/acoustic.png',
        link: "dlw_acoustic.htm",
      },
    ];
  }
  