function PhotoGalleryData() {
  return [
    {
      name: "Клиника «Эксимер»",
      type: "object",
      link: "./photo-eksimer.html",
      image: "./assets/images/photo-gallery/eksimer.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Детский сад «Дюшес»",
      type: "object",
      link: "./photo-dushes.html",
      image: "./assets/images/photo-gallery/dushes.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Фитнес-клуб «World Class»",
      type: "object",
      link: "./world-class.html",
      image: "./assets/images/photo-gallery/world_class.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Торгово-строительная компания «Гельстер»",
      type: "object",
      link: "./office-gelster.html",
      image: "./assets/images/photo-gallery/gelster.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Детский развлекательный клуб «Happy Land»",
      type: "object",
      link: "./photo-happy_land.htm",
      image: "./assets/images/photo-gallery/happy_land.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Государственный Эрмитаж",
      type: "object",
      link: "./photo-hermitage.html",
      image: "./assets/images/photo-gallery/hermitage.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Фитнес-клуб «ФизКульт»",
      type: "object",
      link: "./real-foto-v-physcult.html",
      image: "./assets/images/photo-gallery/physkult.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Стамотология «Петродент»",
      type: "object",
      link: "./real-foto-v-petrodent.html",
      image: "./assets/images/photo-gallery/petrodent.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Дом ветеранов сцены",
      type: "object",
      link: "./real-foto-v-veteran-scene.html",
      image: "./assets/images/photo-gallery/scene.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Детский сад «Воздушный замок»",
      type: "object",
      link: "./real-foto-v-sky-castle.html",
      image: "./assets/images/photo-gallery/castle.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "ЖК 24 29",
      type: "object",
      link: "./real-foto-v-zhk-24.html",
      image: "./assets/images/photo-gallery/zhk.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Столешница из натурального линолеума",
      type: "object",
      link: "./real-foto-v-stoleshnica.html",
      image: "./assets/images/photo-gallery/stoleshnica.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Российский институт радионавигациии времени",
      type: "object",
      link: "./real-foto-v-russian-university.html",
      image: "./assets/images/photo-gallery/univer.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Кухня",
      type: "interior",
      link: "./marmoleum_kuhnya.html",
      image: "./assets/images/photo-gallery/iterior_1.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Спальня",
      type: "interior",
      link: "./marmoleum_srednya_komnata.html",
      image: "./assets/images/photo-gallery/iterior_2.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Прихожая",
      type: "interior",
      link: "./marmoleum_prihozhaya.html",
      image: "./assets/images/photo-gallery/iterior_3.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Кухня",
      type: "interior",
      link: "./marmoleum_kuhnya_1.html",
      image: "./assets/images/photo-gallery/iterior_4.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Спальня",
      type: "interior",
      link: "./marmoleum_srednya_komnata_1.html",
      image: "./assets/images/photo-gallery/iterior_5.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Коридор",
      type: "interior",
      link: "./marmoleum_koridor.html",
      image: "./assets/images/photo-gallery/iterior_6.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Детская комната",
      type: "interior",
      link: "./marmoleum-foto-8-liniya.htm",
      image: "./assets/images/photo-gallery/iterior_7.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Зал",
      type: "interior",
      link: "./marmoleum_zal.html",
      image: "./assets/images/photo-gallery/iterior_8.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Комната в частном доме",
      type: "interior",
      link: "./marmoleum_room_house.html",
      image: "./assets/images/photo-gallery/iterior_9.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
    {
      name: "Гостиная",
      type: "interior",
      link: "./marmoleum_gostinaya.html",
      image: "./assets/images/photo-gallery/iterior_10.png",
      subtitle: "Нажмите, чтобы посмотрть полностью",
    },
  ];
}
