function PhotoGalleryData() {
  return [
    {
      name: "Клиника «Эксимер»",
      type: "object",
      link: "./photo-eksimer.html",
      image: "./assets/images/photo-gallery/eksimer.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Детский сад «Дюшес»",
      type: "object",
      link: "./photo-dushes.html",
      image: "./assets/images/photo-gallery/dushes.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Детский развлекательный клуб «Happy Land»",
      type: "object",
      link: "./photo-happy_land.html",
      image: "./assets/images/photo-gallery/happy_land.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Государственный Эрмитаж",
      type: "object",
      link: "./photo-hermitage.html",
      image: "./assets/images/photo-gallery/hermitage.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Стоматология «Петродент»",
      type: "object",
      link: "./photo-petrodent.html",
      image: "./assets/images/photo-gallery/petrodent.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Фитнес-клуб «World Class»",
      type: "object",
      link: "./photo-world_class.html",
      image: "./assets/images/photo-gallery/world_class.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Спальня",
      type: "interior",
      link: "./photo-flat.html",
      image: "./assets/images/photo-gallery/iterior_5.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Прихожая",
      type: "interior",
      link: "./photo-hallway.html",
      image: "./assets/images/photo-gallery/iterior_3.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Кухня",
      type: "interior",
      link: "./photo-kitchen.html",
      image: "./assets/images/photo-gallery/iterior_4.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Детская комната",
      type: "interior",
      link: "./photo-flat_8_line.html",
      image: "./assets/images/photo-gallery/iterior_7.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Коридор",
      type: "interior",
      link: "./photo-black_plintus.html",
      image: "./assets/images/photo-gallery/iterior_9.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Спальня",
      type: "interior",
      link: "./photo-bedroom.html",
      image: "./assets/images/photo-gallery/iterior_2.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Кухня",
      type: "interior",
      link: "./photo-plitka_imitation.html",
      image: "./assets/images/photo-gallery/iterior_1.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Гостиная",
      type: "interior",
      link: "./photo-flat_design.html",
      image: "./assets/images/photo-gallery/iterior_10.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Российский институт радионавигации",
      type: "interior",
      link: "./photo-rirv.html",
      image: "./assets/images/photo-gallery/univer.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Детский сад «Воздушный замок»",
      type: "interior",
      link: "./photo-child_castle.html",
      image: "./assets/images/photo-gallery/castle.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Зал",
      type: "interior",
      link: "./photo-private_house.html",
      image: "./assets/images/photo-gallery/iterior_8.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Столешница из натурального линолеума",
      type: "interior",
      link: "./photo-stoleshnica.html",
      image: "./assets/images/photo-gallery/stoleshnica.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Дом ветеранов сцены",
      type: "object",
      link: "./photo-veteranov_house.html",
      image: "./assets/images/photo-gallery/scene.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "ЖК 24 29",
      type: "object",
      link: "./photo-zhk_24.html",
      image: "./assets/images/photo-gallery/zhk.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Фитнес-клуб «ФизКульт»",
      type: "object",
      link: "./photo-physcult.html",
      image: "./assets/images/photo-gallery/physkult.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
    {
      name: "Торгово-строительная компания «Гельстер»",
      type: "object",
      link: "./photo-gelster_office.html",
      image: "./assets/images/photo-gallery/gelster.png",
      subtitle: "Нажмите, чтобы посмотреть полностью",
    },
  ];
}
